<?php

namespace app\models;

/**
 * Description of TextConstants
 *
 * @author Avuunita
 */
class TextConstants
{
    const APP = "app";

    const MESSAGE_SELECT_COMPANY = "MESSAGE_SELECT_COMPANY";

    const INDEX = "index";

    const INDEX_WELCOME_APP = "INDEX_WELCOME_APP";
    const INDEX_MESSAGE_WELCOME_APP = "INDEX_MESSAGE_WELCOME_APP";
    const INDEX_CREATE_COMPANY = "INDEX_CREATE_COMPANY";
    const INDEX_MESSAGE_ENTER_COMPANY_1 = "INDEX_MESSAGE_ENTER_COMPANY_1";
    const INDEX_MESSAGE_ENTER_COMPANY_2 = "INDEX_MESSAGE_ENTER_COMPANY_2";
    const INDEX_MESSAGE_PENDING_APPLICATIONS_1 = "INDEX_MESSAGE_PENDING_APPLICATIONS_1";
    const INDEX_MESSAGE_PENDING_APPLICATIONS_2 = "INDEX_MESSAGE_PENDING_APPLICATIONS_2";

    const INDEX_MESSAGE_ACTIVATE_ACCOUNT = "INDEX_MESSAGE_ACTIVATE_ACCOUNT";
    const INDEX_MESSAGE_USER_STATUS = "INDEX_MESSAGE_USER_STATUS";

    const INDEX_CONTINUE = "INDEX_CONTINUE";

    const INDEX_COMPANIES_TITLE = "INDEX_COMPANIES_TITLE";
    const INDEX_COMPANIES_PARAGRAPH_1 = "INDEX_COMPANIES_PARAGRAPH_1";
    const INDEX_COMPANIES_PARAGRAPH_2 = "INDEX_COMPANIES_PARAGRAPH_2";
    const INDEX_SELECTED_COMPANY = "INDEX_SELECTED_COMPANY";

    const INDEX_DOCUMENTS_TITLE = "INDEX_DOCUMENTS_TITLE";
    const INDEX_DOCUMENTS_PARAGRAPH = "INDEX_DOCUMENTS_PARAGRAPH";
    const INDEX_PRODUCTS_TITLE = "INDEX_PRODUCTS_TITLE";
    const INDEX_PRODUCTS_PARAGRAPH = "INDEX_PRODUCTS_PARAGRAPH";
    const INDEX_WAREHOUSES_TITLE = "INDEX_WAREHOUSES_TITLE";
    const INDEX_WAREHOUSES_PARAGRAPH = "INDEX_WAREHOUSES_PARAGRAPH";
    const INDEX_SUPPLIERS_TITLE = "INDEX_SUPPLIERS_TITLE";
    const INDEX_SUPPLIERS_PARAGRAPH = "INDEX_SUPPLIERS_PARAGRAPH";
    const INDEX_TRANSACTIONS_TITLE = "INDEX_TRANSACTIONS_TITLE";
    const INDEX_TRANSACTIONS_PARAGRAPH = "INDEX_TRANSACTIONS_PARAGRAPH";
    const INDEX_EXISTENCES_TITLE = "INDEX_EXISTENCES_TITLE";
    const INDEX_EXISTENCES_PARAGRAPH = "INDEX_EXISTENCES_PARAGRAPH";
    const INDEX_KARDEX_TITLE = "INDEX_KARDEX_TITLE";
    const INDEX_KARDEX_PARAGRAPH = "INDEX_KARDEX_PARAGRAPH";

    const STATUS = "status";

    const STATUS_ACTIVE = "STATUS_ACTIVE";
    const STATUS_INACTIVE = "STATUS_INACTIVE";
    const STATUS_NULLED = "STATUS_NULLED";
    const STATUS_DRAFT = "STATUS_DRAFT";
}