<?php

namespace app\models;

/**
 * Description of TextConstants
 *
 * @author Avuunita
 */
class TextConstants
{
    /**
     * Category: app
     * @var string
     */
    const APP = "app";

    const MESSAGE_SELECT_COMPANY = "MESSAGE_SELECT_COMPANY";
    const MESSAGE_CONFIRMATION_DELETE = "MESSAGE_CONFIRMATION_DELETE";
    const MESSAGE_VALIDATE_PHONE = "MESSAGE_VALIDATE_PHONE";
    const MESSAGE_PASSWORD_VALIDATION = "MESSAGE_PASSWORD_VALIDATION";
    const MESSAGE_PASSWORDS_NOT_MATCH = "MESSAGE_PASSWORDS_NOT_MATCH";
    const MESSAGE_PAGE_NOT_EXISTS = "MESSAGE_PAGE_NOT_EXISTS";
    const MESSAGE_INCORRECT_LOGIN = "MESSAGE_INCORRECT_LOGIN";

    const MESSAGE_NON_ACTIVE_USER = "MESSAGE_NON_ACTIVE_USER";
    const MESSAGE_NOT_ENOUGH_PERMISSIONS = "MESSAGE_NOT_ENOUGH_PERMISSIONS";

    const BUTTON_SELECT = "BUTTON_SELECT";
    const BUTTON_CREATE = "BUTTON_CREATE";
    const BUTTON_VIEW = "BUTTON_VIEW";
    const BUTTON_UPDATE = "BUTTON_UPDATE";
    const BUTTON_SAVE = "BUTTON_SAVE";
    const BUTTON_APPROVE = "BUTTON_APPROVE";
    const BUTTON_DENY = "BUTTON_DENY";
    const BUTTON_DEACTIVATE = "BUTTON_DEACTIVATE";
    const BUTTON_ACTIVATE = "BUTTON_ACTIVATE";

    const OPTION_SELECT = "OPTION_SELECT";
    const OPTION_YES = "OPTION_YES";
    const OPTION_NO = "OPTION_NO";
    const OPTION_ALL = "OPTION_ALL";

    /**
     * Category: index
     * @var string
     */
    const INDEX = "index";

    const INDEX_WELCOME_APP = "INDEX_WELCOME_APP";
    const INDEX_MESSAGE_WELCOME_APP = "INDEX_MESSAGE_WELCOME_APP";
    const INDEX_CREATE_COMPANY = "INDEX_CREATE_COMPANY";
    const INDEX_MESSAGE_ENTER_COMPANY_1 = "INDEX_MESSAGE_ENTER_COMPANY_1";
    const INDEX_MESSAGE_ENTER_COMPANY_2 = "INDEX_MESSAGE_ENTER_COMPANY_2";
    const INDEX_MESSAGE_PENDING_APPLICATIONS_1 = "INDEX_MESSAGE_PENDING_APPLICATIONS_1";
    const INDEX_MESSAGE_PENDING_APPLICATIONS_2 = "INDEX_MESSAGE_PENDING_APPLICATIONS_2";

    const INDEX_MESSAGE_ACTIVATE_ACCOUNT = "INDEX_MESSAGE_ACTIVATE_ACCOUNT";
    const INDEX_MESSAGE_USER_STATUS = "INDEX_MESSAGE_USER_STATUS";

    const INDEX_CONTINUE = "INDEX_CONTINUE";

    const INDEX_COMPANIES_TITLE = "INDEX_COMPANIES_TITLE";
    const INDEX_COMPANIES_PARAGRAPH_1 = "INDEX_COMPANIES_PARAGRAPH_1";
    const INDEX_COMPANIES_PARAGRAPH_2 = "INDEX_COMPANIES_PARAGRAPH_2";
    const INDEX_SELECTED_COMPANY = "INDEX_SELECTED_COMPANY";

    const INDEX_DOCUMENTS_TITLE = "INDEX_DOCUMENTS_TITLE";
    const INDEX_DOCUMENTS_PARAGRAPH = "INDEX_DOCUMENTS_PARAGRAPH";
    const INDEX_PRODUCTS_TITLE = "INDEX_PRODUCTS_TITLE";
    const INDEX_PRODUCTS_PARAGRAPH = "INDEX_PRODUCTS_PARAGRAPH";
    const INDEX_WAREHOUSES_TITLE = "INDEX_WAREHOUSES_TITLE";
    const INDEX_WAREHOUSES_PARAGRAPH = "INDEX_WAREHOUSES_PARAGRAPH";
    const INDEX_SUPPLIERS_TITLE = "INDEX_SUPPLIERS_TITLE";
    const INDEX_SUPPLIERS_PARAGRAPH = "INDEX_SUPPLIERS_PARAGRAPH";
    const INDEX_TRANSACTIONS_TITLE = "INDEX_TRANSACTIONS_TITLE";
    const INDEX_TRANSACTIONS_PARAGRAPH = "INDEX_TRANSACTIONS_PARAGRAPH";
    const INDEX_EXISTENCES_TITLE = "INDEX_EXISTENCES_TITLE";
    const INDEX_EXISTENCES_PARAGRAPH = "INDEX_EXISTENCES_PARAGRAPH";
    const INDEX_KARDEX_TITLE = "INDEX_KARDEX_TITLE";
    const INDEX_KARDEX_PARAGRAPH = "INDEX_KARDEX_PARAGRAPH";

    /**
     * Category: company
     * @var string
     */
    const COMPANY = "company";

    const COMPANY_MESSAGE_OWNER_NOT_DEMOTE = "COMPANY_MESSAGE_OWNER_NOT_DEMOTE";
    const COMPANY_MESSAGE_CANNOT_PROMOTE_INACTIVE = "COMPANY_MESSAGE_CANNOT_PROMOTE_INACTIVE";
    const COMPANY_MESSAGE_CANNOT_ACTIVATE_YOURSELF = "COMPANY_MESSAGE_CANNOT_ACTIVATE_YOURSELF";
    const COMPANY_MESSAGE_OWNER_NOT_ACTIVATE = "COMPANY_MESSAGE_OWNER_NOT_ACTIVATE";
    const COMPANY_MESSAGE_CANNOT_ACTIVATE_SUPERVISORS = "COMPANY_MESSAGE_CANNOT_ACTIVATE_SUPERVISORS";
    const COMPANY_MESSAGE_INFO_NOT_BELONG_COMPANY = "COMPANY_MESSAGE_INFO_NOT_BELONG_COMPANY";

    const COMPANY_INDEX_TITLE = "COMPANY_INDEX_TITLE";
    const COMPANY_INDEX_TEXT = "COMPANY_INDEX_TEXT";
    const COMPANY_INDEX_CREATE = "COMPANY_INDEX_CREATE";
    const COMPANY_INDEX_UPDATE = "COMPANY_INDEX_UPDATE";
    const COMPANY_INDEX_BUTTON_LIST_USERS = "COMPANY_INDEX_BUTTON_LIST_USERS";
    const COMPANY_INDEX_BUTTON_CREATE_USER = "COMPANY_INDEX_BUTTON_CREATE_USER";
    const COMPANY_INDEX_CONFIRMATION_SELECT = "COMPANY_INDEX_CONFIRMATION_SELECT";

    const COMPANY_INDEX_OTHER_TITLE = "COMPANY_INDEX_OTHER_TITLE";
    const COMPANY_INDEX_OTHER_TEXT = "COMPANY_INDEX_OTHER_TEXT";
    const COMPANY_INDEX_BUTTON_SHOW_APPLICATIONS = "COMPANY_INDEX_BUTTON_SHOW_APPLICATIONS";

    const COMPANY_VIEW_TITLE = "COMPANY_VIEW_TITLE";

    const COMPANY_LIST_USERS_TITLE = "COMPANY_LIST_USERS_TITLE";
    const COMPANY_BUTTON_CREATE_USER = "COMPANY_BUTTON_CREATE_USER";
    const COMPANY_LIST_USERS_PENDING = "COMPANY_LIST_USERS_PENDING";

    const COMPANY_USERS_PROMOTE = "COMPANY_USERS_PROMOTE";
    const COMPANY_USERS_CONFIRMATION_PROMOTE = "COMPANY_USERS_CONFIRMATION_PROMOTE";
    const COMPANY_USERS_DEMOTE = "COMPANY_USERS_DEMOTE";
    const COMPANY_USERS_CONFIRMATION_DEMOTE = "COMPANY_USERS_CONFIRMATION_DEMOTE";
    const COMPANY_USERS_PROMOTE_SUPERVISOR = "COMPANY_USERS_PROMOTE_SUPERVISOR";
    const COMPANY_USERS_DEMOTE_MEMBER = "COMPANY_USERS_DEMOTE_MEMBER";
    const COMPANY_USERS_CONFIRMATION_DEACTIVATE = "COMPANY_USERS_CONFIRMATION_DEACTIVATE";
    const COMPANY_USERS_CONFIRMATION_ACTIVATE = "COMPANY_USERS_CONFIRMATION_ACTIVATE";
    const COMPANY_USERS_CONFIRMATION_APPROVE = "COMPANY_USERS_CONFIRMATION_APPROVE";
    const COMPANY_USERS_DENY = "COMPANY_USERS_DENY";
    const COMPANY_USERS_MESSAGE_FEEDBACK = "COMPANY_USERS_MESSAGE_FEEDBACK";

    const COMPANY_MODEL_ID = "COMPANY_MODEL_ID";
    const COMPANY_MODEL_CODE = "COMPANY_MODEL_CODE";
    const COMPANY_MODEL_STATUS = "COMPANY_MODEL_STATUS";
    const COMPANY_MODEL_YOUR_STATUS = "COMPANY_MODEL_YOUR_STATUS";
    const COMPANY_MODEL_USER_STATUS = "COMPANY_MODEL_USER_STATUS";
    const COMPANY_MODEL_STATUS_IN_COMPANY = "COMPANY_MODEL_STATUS_IN_COMPANY";
    const COMPANY_MODEL_POSITION = "COMPANY_MODEL_POSITION";
    const COMPANY_MODEL_ROLE = "COMPANY_MODEL_ROLE";

    /**
     * Category: user
     * @var string
     */
    const USER = "user";
    const USER_MODEL_ID = "USER_MODEL_ID";
    const USER_MODEL_PASSWORD = "USER_MODEL_PASSWORD";
    const USER_MODEL_REPASSWORD = "USER_MODEL_REPASSWORD";

    /**
     * Category: application
     * @var string
     */
    const APPLICATION = "application";

    const COMPANY_APPLICATION_MESSAGE_COMMENT = "COMPANY_APPLICATION_MESSAGE_COMMENT";
    const APPLICATION_MESSAGE_NOT_CREATE_NEW_APPLICATION_EXISTING_PENDING = "APPLICATION_MESSAGE_NOT_CREATE_NEW_APPLICATION_EXISTING_PENDING";

    const COMPANY_APPLICATIONS_TITLE = "COMPANY_APPLICATIONS_TITLE";
    const COMPANY_BUTTON_CREATE_APPLICATION = "COMPANY_BUTTON_CREATE_APPLICATION";
    const COMPANY_VIEW_APPLICATION_COMPANY_TITLE = "COMPANY_VIEW_APPLICATION_COMPANY_TITLE";
    const COMPANY_VIEW_APPLICATION_USER_TITLE = "COMPANY_VIEW_APPLICATION_USER_TITLE";

    const APPLICATION_MODEL_ID = "APPLICATION_MODEL_ID";
    const APPLICATION_MODEL_COMMENT = "APPLICATION_MODEL_COMMENT";
    const APPLICATION_MODEL_FEEDBACK = "APPLICATION_MODEL_FEEDBACK";
    const APPLICATION_MODEL_SENT_AT = "APPLICATION_MODEL_SENT_AT";

    /**
     * Category: supplier
     * @var string
     */
    const SUPPLIER = "supplier";

    const SUPPLIER_INDEX_CONFIRMATION_DEACTIVATE = "SUPPLIER_INDEX_CONFIRMATION_DEACTIVATE";
    const SUPPLIER_INDEX_CONFIRMATION_ACTIVATE = "SUPPLIER_INDEX_CONFIRMATION_ACTIVATE";

    const SUPPLIER_MODEL_ID = "SUPPLIER_MODEL_ID";

    /**
     * Category: warehouse
     * @var string
     */
    const WAREHOUSE = "warehouse";

    const WAREHOUSE_INDEX_CONFIRMATION_DEACTIVATE = "WAREHOUSE_INDEX_CONFIRMATION_DEACTIVATE";
    const WAREHOUSE_INDEX_CONFIRMATION_ACTIVATE = "WAREHOUSE_INDEX_CONFIRMATION_ACTIVATE";

    const WAREHOUSE_MODEL_ID = "WAREHOUSE_MODEL_ID";

    /**
     * Category: product
     * @var string
     */
    const PRODUCT = "product";

    const PRODUCT_INDEX_CONFIRMATION_DEACTIVATE = "PRODUCT_INDEX_CONFIRMATION_DEACTIVATE";
    const PRODUCT_INDEX_CONFIRMATION_ACTIVATE = "PRODUCT_INDEX_CONFIRMATION_ACTIVATE";

    const PRODUCT_MODEL_ID = "PRODUCT_MODEL_ID";
    const PRODUCT_MODEL_HAS_EXISTENCES = "PRODUCT_MODEL_HAS_EXISTENCES";
    const PRODUCT_MODEL_TAX_RATE = "PRODUCT_MODEL_TAX_RATE";
    const PRODUCT_MODEL_DISCOUNT_RATE = "PRODUCT_MODEL_DISCOUNT_RATE";
    const PRODUCT_MODEL_MINIMUM_STOCK = "PRODUCT_MODEL_MINIMUM_STOCK";
    const PRODUCT_MODEL_SUGGESTED_VALUE = "PRODUCT_MODEL_SUGGESTED_VALUE";

    /**
     * Category: document
     * @var string
     */
    const DOCUMENT = "document";

    const DOCUMENT_INDEX_CONFIRMATION_DEACTIVATE = "DOCUMENT_INDEX_CONFIRMATION_DEACTIVATE";
    const DOCUMENT_INDEX_CONFIRMATION_ACTIVATE = "DOCUMENT_INDEX_CONFIRMATION_ACTIVATE";

    const DOCUMENT_ACTION_INTENDED_INPUT = "DOCUMENT_ACTION_INTENDED_INPUT";
    const DOCUMENT_ACTION_INTENDED_OUTPUT = "DOCUMENT_ACTION_INTENDED_OUTPUT";
    const DOCUMENT_APPLY_SUPPLIER = "DOCUMENT_APPLY_SUPPLIER";
    const DOCUMENT_APPLY_CUSTOMER = "DOCUMENT_APPLY_CUSTOMER";

    const DOCUMENT_MODEL_ID = "DOCUMENT_MODEL_ID";
    const DOCUMENT_MODEL_INTENDED_FOR = "DOCUMENT_MODEL_INTENDED_FOR";
    const DOCUMENT_MODEL_APPLY_FOR = "DOCUMENT_MODEL_APPLY_FOR";
    const DOCUMENT_MODEL_HAS_TAXES = "DOCUMENT_MODEL_HAS_TAXES";
    const DOCUMENT_MODEL_HAS_EXPIRATION = "DOCUMENT_MODEL_HAS_EXPIRATION";
    const DOCUMENT_MODEL_HAS_OTHER_TRANSACTION = "DOCUMENT_MODEL_HAS_OTHER_TRANSACTION";

    /**
     * Category: transaction
     * @var string
     */
    const TRANSACTION = "transaction";

    const TRANSACTION_MESSAGE_INFO_DELETED_NOT_DRAFT_TRANSACTION = "TRANSACTION_MESSAGE_INFO_DELETED_NOT_DRAFT_TRANSACTION";

    /**
     * Category: city
     * @var string
     */
    const CITY = "city";
    const CITY_MODEL_ID = "CITY_MODEL_ID";

    /**
     * Category: state
     * @var string
     */
    const STATE = "state";
    const STATE_MODEL_ID = "STATE_MODEL_ID";

    /**
     * Category: country
     * @var string
     */
    const COUNTRY = "country";
    const COUNTRY_MODEL_ID = "COUNTRY_MODEL_ID";

    /**
     * Category: attribute
     * @var string
     */
    const ATTRIBUTE = "attribute";
    const ATTRIBUTE_MODEL_CODE = "ATTRIBUTE_MODEL_CODE";
    const ATTRIBUTE_MODEL_NAME = "ATTRIBUTE_MODEL_NAME";
    const ATTRIBUTE_MODEL_PHONE = "ATTRIBUTE_MODEL_PHONE";
    const ATTRIBUTE_MODEL_ADDRESS = "ATTRIBUTE_MODEL_ADDRESS";
    const ATTRIBUTE_MODEL_EMAIL = "ATTRIBUTE_MODEL_EMAIL";
    const ATTRIBUTE_MODEL_DESCRIPTION = "ATTRIBUTE_MODEL_DESCRIPTION";

    const ATTRIBUTE_MODEL_STATUS = "ATTRIBUTE_MODEL_STATUS";
    const ATTRIBUTE_MODEL_CREATED_BY = "ATTRIBUTE_MODEL_CREATED_BY";
    const ATTRIBUTE_MODEL_CREATED_AT = "ATTRIBUTE_MODEL_CREATED_AT";
    const ATTRIBUTE_MODEL_UPDATED_BY = "ATTRIBUTE_MODEL_UPDATED_BY";
    const ATTRIBUTE_MODEL_UPDATED_AT = "ATTRIBUTE_MODEL_UPDATED_AT";

    /**
     * Category: status
     * @var string
     */
    const STATUS = "status";

    const STATUS_ACTIVE = "STATUS_ACTIVE";
    const STATUS_INACTIVE = "STATUS_INACTIVE";
    const STATUS_NULLED = "STATUS_NULLED";
    const STATUS_DRAFT = "STATUS_DRAFT";
    const STATUS_APPROVED = "STATUS_APPROVED";
    const STATUS_REJECTED = "STATUS_REJECTED";
    const STATUS_PENDING = "STATUS_PENDING";

    /**
     * Category: role
     * @var string
     */
    const ROLE = "role";

    const ROLE_OWNER = "ROLE_OWNER";
    const ROLE_SUPERVISOR = "ROLE_SUPERVISOR";
    const ROLE_MEMBER = "ROLE_MEMBER";
}